apiVersion: batch/v1
kind: Job
metadata:
  name: db-reset-job
spec:
  template:
    spec:
      containers:
        - name: db-reset
          image: postgres:15
          command: ["psql"]
          args:
            [
              "-h", "postgres-service",
              "-U", "miniapiuser",
              "-d", "postgres",
              "-f", "/scripts/reset.sql"
            ]
          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - name: reset-sql
              mountPath: /scripts
      restartPolicy: Never
      volumes:
        - name: reset-sql
          configMap:
            name: reset-sql-config
