apiVersion: v1
kind: Secret
metadata:
  name: swagger-secret
type: Opaque
data:
  # Base64 encoded credentials
  # Default: admin / secret
  # To generate: echo -n "your-value" | base64
  SWAGGER_USER: YWRtaW4=   # "admin" en base64
  SWAGGER_PASS: c2VjcmV0   # "secret" en base64
