apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-api-ts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mini-api-ts
  template:
    metadata:
      labels:
        app: mini-api-ts
    spec:
      containers:
        - name: mini-api-ts
          image: otshudi/mini-api-ts:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret